spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/gulimall_ums?useUnicode=true&characterEncoding=UTF-8&serverTimezone=America/Chicago
    username: root
    password: "0602"
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8849
        username: nacos
        password: "nacos"
    redis:
      host: localhost
      port: 6380
    session:
      store-type: redis
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss

  application:
    name: member

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 8000

thread:
  core-size: 20
  max-size: 200
  keep-alive-time: 10