spring:
  application:
    name: third-party
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
      discovery:
        server-addr: localhost:8848

server:
  port: 16000

#  String host = "https://gyytz.market.alicloudapi.com";
#  String path = "/sms/smsSend";