spring:
  application:
    name: third-party
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8849
        username: nacos
        password: "nacos"

server:
  port: 16000

#  String host = "https://gyytz.market.alicloudapi.com";
#  String path = "/sms/smsSend";