spring:
  application:
    name: search
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
      discovery:
        server-addr: localhost:8848
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6380

server:
  port: 13000