spring:
  application:
    name: search
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8849
        username: nacos
        password: "nacos"
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6380

server:
  port: 13000